version: '3.7'

services:
  nginx:
    build: './.docker/local/nginx'
    container_name: zuu-nginx
    ports:
      - '80:80'
    volumes:
      - ./public:/app/public
      - ./.docker/local/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app

  app:
    build: './.docker/local/php'
    container_name: zuu-app
    working_dir: /app
    volumes:
      - '.:/app'
      - './.docker/local/php/php.ini:/usr/local/etc/php/conf.d/php.ini'
    ports:
      - '9000:9000'
    depends_on:
      - mysql
